export const mockNews = [
  {
    id: 1,
    title: 'Обновление 1.0.1: новые анимации',
    date: '2025-09-01',
    description: 'Мы добавили более плавные переходы и улучшили интерфейс, чтобы играть стало приятнее.',
    image: import.meta.env.BASE_URL + 'images/update.webp',
  },
  {
    id: 2,
    title: 'Ежедневные бонусы!',
    date: '2025-08-28',
    description: 'Заходите каждый день и получайте монеты. Чем дольше серия, тем больше награда!',
    image: import.meta.env.BASE_URL + 'images/daily-bonus.webp',
  },
  {
    id: 3,
    title: 'Соревнование недели',
    date: '2025-08-24',
    description: 'Попробуйте набрать максимальный счёт и попадите в топ игроков. Победители получат дополнительные монеты.',
    image: import.meta.env.BASE_URL + 'images/week.webp',
  },
  {
    id: 4,
    title: 'Темная тема',
    date: '2025-08-17',
    description: 'Теперь можно переключиться на ночной режим. Идеально для вечерних игр.',
    image: import.meta.env.BASE_URL + 'images/dark-light.webp',
  },
  {
    id: 5,
    title: 'Мини-игра дня',
    date: '2025-08-09',
    description: 'Каждый день выбирается особая игра. За победы в ней вы получите удвоенные монеты.',
    image: import.meta.env.BASE_URL + 'images/first.jpg',
  },
  {
    id: 6,
    title: 'Мелкие правки и улучшения',
    date: '2025-08-01',
    description: 'Мы поработали над скоростью загрузки и стабильностью приложений.',
    image: import.meta.env.BASE_URL + 'images/mini-update.webp',
  },
  {
    id: 7,
    title: 'Тестовый турнир',
    date: '2025-07-26',
    description: 'В воскресенье стартует пробный турнир. Примите участие и заработайте редкие награды.',
    image: import.meta.env.BASE_URL + 'images/battle.webp',
  },
  {
    id: 8,
    title: 'Новые достижения',
    date: '2025-07-20',
    description: 'Теперь можно открывать бейджи за выполнение заданий. Попробуйте собрать коллекцию!',
    image: import.meta.env.BASE_URL + 'images/cubok.webp',
  },
  {
    id: 9,
    title: 'Тематическая неделя',
    date: '2025-07-18',
    description: 'На этой неделе особая подборка игр. За победы в них начисляются бонусные монеты.',
    image: import.meta.env.BASE_URL + 'images/bonus.webp',
  },
  {
    id: 10,
    title: 'Обновление профиля',
    date: '2025-07-06',
    description: 'Теперь можно изменить аватар и ник прямо в приложении.',
    image: import.meta.env.BASE_URL + 'images/profile.webp',
  },
];